version: "3.7"

networks:
  proxy:
    external: true
    name: proxy

services:
  proxy:
    container_name: proxy
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /volumes/vhost.d:/etc/nginx/vhost.d/
      - /volumes/conf.d:/etc/nginx/conf.d/
      - /volumes/certs:/etc/nginx/certs
      - /volumes/html:/usr/share/nginx/html
    networks:
      - proxy
    environment:
      - TZ=America/Sao_Paulo

  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: nginxproxy/nginx-letsencrypt
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /volumes/vhost.d:/etc/nginx/vhost.d/
      - /volumes/certs:/etc/nginx/certs
      - /volumes/html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=proxy
      - TZ=America/Sao_Paulo
